name: Filter Proxies

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  filter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Run filter script
        run: node filterProxies.js
        
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ProxyList.txt kvProxyList.json
          git commit -m "Update filtered proxy lists" || echo "No changes to commit"
          git push
